### ISSUE TITLE
The argument name for function get_events does not work

### ISSUE THREAD

**Issue by rvdvelpe** [sysdiglabs/sysdig-sdk-python#113]
I tried version 0.8.0 until 0.10.0 and I always retrieve all the results when I execute the function get_events with the argument name filled in.

It seems like the arguments from_ts, to_ts and tags works.

**Comment by tembleking** [comment]
Hello @rvdvelpe, thanks for your feedback!
Latest version as of today is v0.12.0, can you give it a try?
The new version of the events client is v2, please take a look at the usage in this test:

https://github.com/sysdiglabs/sysdig-sdk-python/blob/443bbca2d955813600c66849c2fbfc067b9eb1e4/specs/monitor/events_v2_spec.py#L69-L73
