### ISSUE TITLE
No methods for getting all notification channels or getting a single alert

### ISSUE THREAD

**Issue by ghost** [sysdiglabs/sysdig-sdk-python#34]
I had a need recently for both of these methods and ended up writing my own. Is this something that I can open a PR for and contribute back to the project? Just wanted to check first beforehand.

Basically, the signature for the methods I wrote:

```py
def get_notification_channels():
  # return list of channels

def get_alert(id):
  # return dictionary containing fields for single alert identified by 'id'
```

Thanks!

**Comment by philrz** [comment]
@tjboring,

Yes, we certainly appreciate contributions, and those sound useful. However, to accept a PR, we'll need you to review & follow the Contributor License Agreements. You can read it at https://github.com/draios/sysdig#contributor-license-agreements. Thanks.

**Comment by tembleking** [comment]
Closing this issue since it's 3 years old.
