### ISSUE TITLE
viewName in create_dashboard_from_view

### ISSUE THREAD

**Issue by williamyeh** [sysdiglabs/sysdig-sdk-python#59]
I have problem filling in values for viewName parameter for create_dashboard_from_view function.
In your document says look for the view in my explore page.
However, I did not find anything called view on my explore page.
There is just groupings to parse my infrastructure. 
Help would be appreciated thanks.

**Comment by philrz** [comment]
@williamyeh: Alas, you've stumbled onto a part of our Python client that got out of sync with the current backend API. I've flagged the problem with appropriate developers and will update this issue once we've addressed it.

**Comment by tembleking** [comment]
Closing this issue since it had no updates for 2 years. If this problem persists, please open a new issue.
Thanks!
