### ISSUE TITLE
Working of edit_team

### ISSUE THREAD

**Issue by saiharshitachava** [sysdiglabs/sysdig-sdk-python#65]
I was trying to use the function of edit team where it overrided all the existing users and added the new user to the team

So currently the previous users were all gone and only the new user I added is there in the team,

Can someone help me in checking the functionality of edit_team? Used the below

https://github.com/draios/python-sdc-client/blob/master/examples/user_team_mgmt.py

**Comment by figarocorso** [comment]
Hello @saiharshitachava , might you provide the following information?
* `get_team` information before updating it
* The `membership` variable you are passing as parameter to the `edit_team` call
* `get_team` information after updating it

**Comment by tembleking** [comment]
I am closing this issue since it's 2 years old.
Please, check the latest version of the plugin and if you find something not working properly, don't hesitate to open a new issue.

Thanks!
